package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePrecisionInventoryDebugging<M extends BasePrecisionInventoryDebugging<M>> extends Model<M> implements IBean {

	/**
	 * id
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 产品二维码
	 */
	public M setQrcode(java.lang.String qrcode) {
		set("qrcode", qrcode);
		return (M)this;
	}
	
	/**
	 * 产品二维码
	 */
	public java.lang.String getQrcode() {
		return getStr("qrcode");
	}

	/**
	 * 产品名称
	 */
	public M setPartName(java.lang.String partName) {
		set("part_name", partName);
		return (M)this;
	}
	
	/**
	 * 产品名称
	 */
	public java.lang.String getPartName() {
		return getStr("part_name");
	}

	/**
	 * 入库时间
	 */
	public M setEntryDate(java.util.Date entryDate) {
		set("entry_date", entryDate);
		return (M)this;
	}
	
	/**
	 * 入库时间
	 */
	public java.util.Date getEntryDate() {
		return get("entry_date");
	}

	/**
	 * 入库操作人
	 */
	public M setEntryPerson(java.lang.String entryPerson) {
		set("entry_person", entryPerson);
		return (M)this;
	}
	
	/**
	 * 入库操作人
	 */
	public java.lang.String getEntryPerson() {
		return getStr("entry_person");
	}

	/**
	 * 入库工序
	 */
	public M setEntryOperation(java.lang.String entryOperation) {
		set("entry_operation", entryOperation);
		return (M)this;
	}
	
	/**
	 * 入库工序
	 */
	public java.lang.String getEntryOperation() {
		return getStr("entry_operation");
	}

	/**
	 * 出库工序
	 */
	public M setDeliveryOperation(java.lang.String deliveryOperation) {
		set("delivery_operation", deliveryOperation);
		return (M)this;
	}
	
	/**
	 * 出库工序
	 */
	public java.lang.String getDeliveryOperation() {
		return getStr("delivery_operation");
	}

	/**
	 * 出库时间
	 */
	public M setDeliveryDate(java.util.Date deliveryDate) {
		set("delivery_date", deliveryDate);
		return (M)this;
	}
	
	/**
	 * 出库时间
	 */
	public java.util.Date getDeliveryDate() {
		return get("delivery_date");
	}

	/**
	 * 出库负责人
	 */
	public M setDeliveryPerson(java.lang.String deliveryPerson) {
		set("delivery_person", deliveryPerson);
		return (M)this;
	}
	
	/**
	 * 出库负责人
	 */
	public java.lang.String getDeliveryPerson() {
		return getStr("delivery_person");
	}

}
