package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseValveEntry<M extends BaseValveEntry<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPartNo(java.lang.String partNo) {
		set("part_no", partNo);
		return (M)this;
	}
	
	public java.lang.String getPartNo() {
		return getStr("part_no");
	}

	public M setPartName(java.lang.String partName) {
		set("part_name", partName);
		return (M)this;
	}
	
	public java.lang.String getPartName() {
		return getStr("part_name");
	}

	public M setEntryQty(java.lang.Integer entryQty) {
		set("entry_qty", entryQty);
		return (M)this;
	}
	
	public java.lang.Integer getEntryQty() {
		return getInt("entry_qty");
	}

	public M setEntryTime(java.util.Date entryTime) {
		set("entry_time", entryTime);
		return (M)this;
	}
	
	public java.util.Date getEntryTime() {
		return get("entry_time");
	}

	public M setOperator(java.lang.String operator) {
		set("operator", operator);
		return (M)this;
	}
	
	public java.lang.String getOperator() {
		return getStr("operator");
	}

}
