package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRpKpiTarget<M extends BaseRpKpiTarget<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 年关闭率
	 */
	public M setYearlyCloseRateTarget(java.lang.Float yearlyCloseRateTarget) {
		set("yearly_close_rate_target", yearlyCloseRateTarget);
		return (M)this;
	}
	
	/**
	 * 年关闭率
	 */
	public java.lang.Float getYearlyCloseRateTarget() {
		return getFloat("yearly_close_rate_target");
	}

	/**
	 * 审核率
	 */
	public M setCheckRateTarget(java.lang.Float checkRateTarget) {
		set("check_rate_target", checkRateTarget);
		return (M)this;
	}
	
	/**
	 * 审核率
	 */
	public java.lang.Float getCheckRateTarget() {
		return getFloat("check_rate_target");
	}

	/**
	 * 人均
	 */
	public M setAverageTarget(java.lang.Float averageTarget) {
		set("average_target", averageTarget);
		return (M)this;
	}
	
	/**
	 * 人均
	 */
	public java.lang.Float getAverageTarget() {
		return getFloat("average_target");
	}

	/**
	 * 年度
	 */
	public M setYear(java.lang.Integer year) {
		set("year", year);
		return (M)this;
	}
	
	/**
	 * 年度
	 */
	public java.lang.Integer getYear() {
		return getInt("year");
	}

}
