package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePrecisionTypeDebugging<M extends BasePrecisionTypeDebugging<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 产品序号
	 */
	public M setPartNo(java.lang.String partNo) {
		set("part_no", partNo);
		return (M)this;
	}
	
	/**
	 * 产品序号
	 */
	public java.lang.String getPartNo() {
		return getStr("part_no");
	}

	/**
	 * 产品名称
	 */
	public M setPartName(java.lang.String partName) {
		set("part_name", partName);
		return (M)this;
	}
	
	/**
	 * 产品名称
	 */
	public java.lang.String getPartName() {
		return getStr("part_name");
	}

	/**
	 * 工序
	 */
	public M setOperations(java.lang.String operations) {
		set("operations", operations);
		return (M)this;
	}
	
	/**
	 * 工序
	 */
	public java.lang.String getOperations() {
		return getStr("operations");
	}

}
