package com.ray.common.model;

import com.ray.common.model.base.BasePrecisionInventory;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class PrecisionInventory extends BasePrecisionInventory<PrecisionInventory> {
	//建议将dao放在Service中只用作查询 
	public static final PrecisionInventory dao = new PrecisionInventory().dao();
	//在Service中声明 可直接复制过去使用
	//private PrecisionInventory dao = new PrecisionInventory().dao();  
}
