package com.ray.common.model;

import com.ray.common.model.base.BasePrecisionInventoryDebugging;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class PrecisionInventoryDebugging extends BasePrecisionInventoryDebugging<PrecisionInventoryDebugging> {
	//建议将dao放在Service中只用作查询 
	public static final PrecisionInventoryDebugging dao = new PrecisionInventoryDebugging().dao();
	//在Service中声明 可直接复制过去使用
	//private PrecisionInventoryDebugging dao = new PrecisionInventoryDebugging().dao();  
}
