package com.ray.common.model;

import com.ray.common.model.base.BaseRpKpiTarget;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class RpKpiTarget extends BaseRpKpiTarget<RpKpiTarget> {
	//建议将dao放在Service中只用作查询 
	public static final RpKpiTarget dao = new RpKpiTarget().dao();
	//在Service中声明 可直接复制过去使用
	//private RpKpiTarget dao = new RpKpiTarget().dao();  
}
