package com.ray.common.model;

import com.ray.common.model.base.BaseRpStaffQty;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class RpStaffQty extends BaseRpStaffQty<RpStaffQty> {
	//建议将dao放在Service中只用作查询 
	public static final RpStaffQty dao = new RpStaffQty().dao();
	//在Service中声明 可直接复制过去使用
	//private RpStaffQty dao = new RpStaffQty().dao();  
}
